apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-python-property-ms
  labels:
    app: deployment-python-property-ms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-python-property-ms
  template:
    metadata:
      labels:
        app: deployment-python-property-ms
    spec:
      containers:
      - name: python-property-ms
        image: totank4545/python-property-ms:v1
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: service-python-property-ms
spec:
  selector:
    app: service-python-property-ms
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer